repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: type-check
        name: type check (pyright)
        entry: poetry run pyright
        language: system
        pass_filenames: false
        stages: [pre-push]